### ISSUE TITLE
Update categories to AWRVI 2.0 research

### ISSUE THREAD

**Issue by vlraymond** [gina-alaska/awrvi#165]

**Comment by teknofire** [comment]
So currently we doing AWRVI 1.0, we need to update with the new indicators, showed up in email and should be in basecamp

**Comment by teknofire** [comment]
Vanessa is gonna review the current with the new stuff

**Comment by smacfarlane** [comment]
Reviewing their groupings of numbers I've found a few problems:

Physical Water Quality - Mod Vulnerable (extra 0?)
Physical Water Quality - These probably should be < or > value, rather than hard ranges as some numbers get left out.  i.e.  Which category would you put 0.0195 into?     This comment goes for a lot of the categories that don't have integer values.
